-- 한줄 주석
/*
	여러줄
	주석
*/

-- 오라클은 커서 위치에 따라 실행하는 부분이 달라짐. 또 그 커서 위치에 있는 명령만을 수행함. (자바처럼 처음부터 끝까지 실행하지 않음)

-- 테이블 생성(CREATE)
CREATE TABLE TEST(
	INTDATA NUMBER(4),
	STRDATA VARCHAR2(100)
);

-- 테이블 삭제(DROP)
DROP TABLE TEST;

-- 테이블 수정(ALTER)
-- 컬럼 추가
ALTER TABLE TEST ADD(
	DOUBLEDATA NUMBER(6,2)
);

-- 컬럼 수정
ALTER TABLE TEST MODIFY(
	STRDATA VARCHAR2(300)
);

-- 이름 변경
ALTER TABLE TEST RENAME TO TEST2;
ALTER TABLE TEST2 RENAME TO TEST;

-- 컬럼 이름 변경
ALTER TABLE TEST RENAME COLUMN DOUBLEDATA TO DOBDATA;

-- 컬럼 삭제
ALTER TABLE TEST DROP COLUMN DOBDATA;

DROP TABLE TEST;
----------
DROP TABLE "USER"; 
-- 임의의 이름으로 PK 부여
CREATE TABLE "USER" (  -- String 아님. 오라클에서 String은 'asdfasdf'와 같이 표기하고 ""는 컬럼 등의 이름을 다른 뜻이 있는 단어로 사용하고 싶을 때 씀. EX) CREATE TABLE "CREATE"
	ID VARCHAR2(100) PRIMARY KEY,
	PW VARCHAR2(100),
	NAME VARCHAR2(100)
);

-- 원하는 이름으로 PK(PRIMARY KEY) 부여
CREATE TABLE "USER" (
	ID VARCHAR2(100),
	PW VARCHAR2(100),
	NAME VARCHAR2(100),
	CONSTRAINT USER_PK PRIMARY KEY(ID)
);

-- FK 부여하기
CREATE TABLE PRODUCT(
	NUM NUMBER(7),
	NAME VARCHAR2(100),
	INFO VARCHAR2(2999),
	ID VARCHAR2(100),
	CONSTRAINT PRODUCT_USER_FK FOREIGN KEY(ID) REFERENCES "USER"(ID) -- extends마냥 어디서 참조할지 써줘야함 
);

DROP TABLE "USER";
DROP TABLE PRODUCT;
-------------------
-- 꽃 테이블
-- 꽃 이름(PK)
-- 꽃 색깔
-- 꽃 가격
CREATE TABLE FLOWER(
	FLOWERNAME VARCHAR2(10),
	FLOWERCOLOR VARCHAR2(5),
	FLOWERPRICE NUMBER(5),
	CONSTRAINT FLOWER_PK PRIMARY KEY(FLOWERNAME)
);

-- 화분 테이블
-- 화분 코드
-- 화분 모양
-- 화분 크기
-- 심을 꽃(FK)
-- 화분 가격
CREATE TABLE FLOWERPOT(
	FLOWERPOTCODE VARCHAR2(10),
	FLOWERPOTSHAPE VARCHAR2(10),
	FLOWERPOTSIZE VARCHAR2(10),
	FLOWERNAME VARCHAR2(10),
	FLOWERPOTPRICE NUMBER(5),
	CONSTRAINT FLOWERPOT_FLOWER_FK FOREIGN KEY(FLOWERNAME) REFERENCES FLOWER(FLOWERNAME)
);

DROP TABLE FLOWER;
DROP TABLE FLOWERPOT;
-- 영화 테이블
CREATE TABLE MOVIE(
	MOVIECODE VARCHAR2(20), --PK는 중복되면 안되고 영화 제목은 중복될 가능성이 있기 때문에 따로 고유코드를 만들어서 관리해줘야 함.
	MOVIETITLE VARCHAR2(100),
	MOVIEDIRECTOR VARCHAR2(100),
	MOVIEACTOR VARCHAR2(100),
	MOVIEINFO VARCHAR2(2999),
	MOVIERELEASEDATE DATE,
	MOVIERUNTIME VARCHAR2(10),
	CONSTRAINT MOVIE_PK PRIMARY KEY(MOVIECODE)
);





